services:
  api:
    build: .
    environment:
      - PORT

      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - $PORT:$PORT
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - .data/mysql:/var/lib/mysql
      
